services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: url_shortener
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  web:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=127.0.0.1
      - DB_USER=flaskuser
      - DB_PASSWORD=flaskpass
      - DB_NAME=url_shortener
    depends_on:
      - db
    volumes:
      - .:/url-shortener

volumes:
  db_data:

